# Training settings
name: JNMC_x2
model_type: JNMCModel
scale: 2
num_gpu: 2
manual_seed: 20

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt:
               #path of gt images of the training dataset, e.g., - DIV2K/DIV2K_train_HR
    dataroot_lq:
              # path of gt images of the training dataset
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~


  #Here, you may input the information (e.g., name and path) of the validation dataset during training. Optional.
  val:
    name:             # the name of validation dataset
    type: PairedImageDataset
    dataroot_gt:     # path of gt images of the validation dataset
    dataroot_lq:     # path of low-resolution images of the validation dataset
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: JNMC
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  d_state: 8
  depth: 4
  embed_dim: 40
  jumc_nums: 5
  expand: 2.0
  mlp_ratio: 2.0

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    #lr: !!float 2e-4
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Validation settings. Optional.
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true


# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29502